version: '3'
services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - timescaledb:/var/lib/postgresql

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    links:
      - timescaledb
    volumes:
      - grafana-data:/var/lib/grafana/
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081

volumes:
  timescaledb:
  grafana-data:
